### ISSUE TITLE
I have error codes that I do not know how to fix.

### ISSUE THREAD

**Issue by JoshuaBuker** [SwerveDriveSpecialties/swerve-template#5]
I am very new to this and am having issues deploying code. This is what I am getting.

﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 4 ﻿﻿ [CAN SPARK MAX] WPILib or External HAL Error: CAN: Message not found ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.RuntimeException: Failed to enable voltage compensation: kHALError ﻿﻿ com.swervedrivespecialties.swervelib.rev.RevUtils.checkNeoError(RevUtils.java:10) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 5 ﻿﻿ [CAN SPARK MAX] Unable to retrieve SPARK MAX firmware version for CAN ID: 27. Please verify the deviceID field matches the configured CAN ID of the controller, and that the controller is connected to the CAN Bus. ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 4 ﻿﻿ [CAN SPARK MAX] WPILib or External HAL Error: CAN: Message not found ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.RuntimeException: Failed to enable voltage compensation: kHALError ﻿﻿ com.swervedrivespecialties.swervelib.rev.RevUtils.checkNeoError(RevUtils.java:10) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿

﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 5 ﻿﻿ [CAN SPARK MAX] Unable to retrieve SPARK MAX firmware version for CAN ID: 27. Please verify the deviceID field matches the configured CAN ID of the controller, and that the controller is connected to the CAN Bus. ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 4 ﻿﻿ [CAN SPARK MAX] WPILib or External HAL Error: CAN: Message not found ﻿﻿  ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ Unhandled exception: java.lang.RuntimeException: Failed to enable voltage compensation: kHALError ﻿﻿ com.swervedrivespecialties.swervelib.rev.RevUtils.checkNeoError(RevUtils.java:10) ﻿﻿﻿
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Warning﻿ at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350): Robots should not quit, but yours did! ﻿
﻿﻿﻿﻿﻿﻿﻿﻿ERROR ﻿﻿ 1 ﻿﻿ The startCompetition() method (or methods called by it) should have handled the exception above. ﻿﻿ edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:352) ﻿﻿﻿

﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿
﻿﻿﻿﻿﻿﻿

**Comment by jasondaming** [comment]
Do all of your SPARK MAXs have device ids?  Are all of those ids properly set per step 5 of the [readme](https://github.com/SwerveDriveSpecialties/swerve-template#readme)?

**Comment by JoshuaBuker** [comment]
Yes, I went through and connected to each one with the Rev Spark Client and they all have IDs and I changed the constants for each thing to the correct ID.

**Comment by jasondaming** [comment]
What is CAN ID 27?  Can you double check it?

**Comment by JoshuaBuker** [comment]
CAN ID 27 is our Left Front Drive motor. Checked it in the Rev Client. However, we found out that the sodering on the CANCoders are screwed up, So we are in the process of fixing them. In Phoenix tuner only 1 cancoder shows up, so we are thinking that these things are the issue.
